services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    volumes:
      - ./configuration/postgresql/initdb:/docker-entrypoint-initdb.d
      - postgresqldata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=chirpstack
      - POSTGRES_PASSWORD=chirpstack
      - POSTGRES_DB=chirpstack
    networks:
      - chirp-django-net
    ports:
      - "5432:5432"
volumes:
  postgresqldata:

networks:
  chirp-django-net:
    external: true
