services:
  postgres:
    image: postgres:16-alpine
    restart: always
    env_file:
      - ../.env.prod
    networks:
      - chirp-django-net
    volumes:
      - ./configuration/postgresql/initdb:/docker-entrypoint-initdb.d
      - postgresqldata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}"]
      interval: 30s
      timeout: 10s
      retries: 5
volumes:
  postgresqldata:

networks:
  chirp-django-net:
    external: true
