services:
  redis:
    image: redis:alpine
    restart: always
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    command: redis-server --requirepass redispass
    networks:
      - chirp-django-net

  web:
    build: .
    command: bash -c "python manage.py migrate && python manage.py shell < init_superuser.py && daphne -b 0.0.0.0 -p 8000 drf.asgi:application"
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    ports:
      - "8000:8000"
    environment:
      - DB_NAME=chirpstack
      - DB_USER=chirpstack
      - DB_PASSWORD=chirpstack
      - DB_HOST=persistance-postgres-1
      - DB_PORT=5432
    depends_on:
      - redis
    networks:
      - chirp-django-net

volumes:
  redis_data:
  static_volume:

networks:
  chirp-django-net:
    external: true

