services:
  chirpstack:
    image: chirpstack/chirpstack:4
    user: 1000:1000
    command: -c /etc/chirpstack
    restart: always
    env_file:
      - .env.prod
    depends_on:
      - mosquitto
      - redis
    ports:
      - "8080:8080"
    networks:
      - chirp-django-net
    volumes:
      - ./configuration/chirpstack:/etc/chirpstack
      - ../../.certs:/etc/chirpstack/certs
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "8080"]
      interval: 30s
      timeout: 10s
      retries: 3

  chirpstack-gateway-bridge:
    image: chirpstack/chirpstack-gateway-bridge:4
    restart: always
    ports:
      - "1700:1700/udp"  # Solo si es necesario
    volumes:
      - ./configuration/chirpstack-gateway-bridge:/etc/chirpstack-gateway-bridge
    env_file:
      - .env.prod
    networks:
      - chirp-django-net
    depends_on:
      - mosquitto

  chirpstack-gateway-bridge-basicstation:
    image: chirpstack/chirpstack-gateway-bridge:4
    restart: always
    command: -c /etc/chirpstack-gateway-bridge/chirpstack-gateway-bridge-basicstation-us915_7.toml
    ports:
      - "3001:3001"  # Solo si los gateways se conectan desde fuera
    volumes:
      - ./configuration/chirpstack-gateway-bridge:/etc/chirpstack-gateway-bridge
    networks:
      - chirp-django-net
    depends_on:
      - mosquitto

  chirpstack-rest-api:
    image: chirpstack/chirpstack-rest-api:4
    restart: always
    command: --server chirpstack:8080 --bind 0.0.0.0:8090 --insecure
    ports:
      - "8090:8090"
    depends_on:
      - chirpstack
    networks:
      - chirp-django-net
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8090/"]
      interval: 30s
      timeout: 10s
      retries: 5

  redis:
    image: redis:7-alpine
    restart: always
    command: redis-server --save 300 1 --save 60 100 --appendonly no
    volumes:
      - redisdata:/data
    networks:
      - chirp-django-net
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  mosquitto:
    image: eclipse-mosquitto:2
    restart: always
    ports:
      - "1883:1883"
    volumes: 
      - ./configuration/mosquitto/config/:/mosquitto/config/
      - ../../.certs:/etc/mosquitto/certs/
    networks:
      - chirp-django-net
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "1883"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  redisdata:

networks:
  chirp-django-net:
    external: true
