services:
  redis:
    image: redis:alpine
    restart: always
    volumes:
      - redis_data:/data
    environment:
      - REDIS_PASSWORD=redispass
    command: >
      sh -c "redis-server 
      --requirepass \"${REDIS_PASSWORD}\" 
      --save 300 1 
      --save 60 100 
      --appendonly no"
    networks:
      - chirp-django-net

  web:
    build: .
    command: bash -c "python manage.py migrate && python manage.py shell < init_superuser.py && daphne -b 0.0.0.0 -p 8000 drf.asgi:application"
    volumes:
      - static_volume:/app/staticfiles
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SECRET_KEY=your_secret_key_here
      - EMAIL_HOST_USER=email@example.com
      - EMAIL_HOST_PASSWORD=password
      - CHIRPSTACK_JWT_TOKEN=your_chipstack_jwt_token_here
      - SUPERUSER_1_USERNAME=admin1
      - SUPERUSER_1_EMAIL=admin1@example.com
      - SUPERUSER_1_PASSWORD=admin1password
      - SUPERUSER_2_USERNAME=admin2
      - SUPERUSER_2_EMAIL=admin2@example.com
      - SUPERUSER_2_PASSWORD=admin2password
      - POSTGRESQL_HOST=persistance-postgres-1
      - POSTGRES_USER=chirpstack
      - POSTGRES_PASSWORD=chirpstack
      - POSTGRES_DB=chirpstack
      - REDIS_PASSWORD=redispass
      - ALLOWED_HOSTS=localhost,127.0.0.1
    depends_on:
      - redis
    networks:
      - chirp-django-net
  
  swagger-ui:
    image: swaggerapi/swagger-ui:latest
    ports:
    - "8010:8080"
    volumes:
    - ../openapi.json:/usr/share/nginx/html/openapi.json
    environment:
      - SWAGGER_JSON_URL=/openapi.json
    restart: always
    networks:
    - chirp-django-net

volumes:
  redis_data:
  static_volume:

networks:
  chirp-django-net:
    external: true

