services:
  paho:
    build: .
    restart: always
    volumes:
      - ../../.certs:/etc/paho-mqtt/certs
    networks:
      - chirp-django-net

networks:
  chirp-django-net:
    external: true  
    
