services:
  paho:
    build: .
    restart: always
    volumes:
      - ../../.certs:/etc/paho-mqtt/certs
    env_file:
      - ../.env.prod
    networks:
      - chirp-django-net
  
    healthcheck:
      test: ["CMD", "python", "/app/health_check.py"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

networks:
  chirp-django-net:
    external: true  