name: Unified Deployment Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-databases:
    uses: ./.github/workflows/deploy_component.yml
    with:
      component-path: 'persistance'
    secrets: inherit

  deploy-lorawan-server:
    needs: deploy-databases
    uses: ./.github/workflows/deploy_component.yml
    with:
      component-path: 'lorawan-server'
    secrets: inherit

  deploy-mqtt-client:
    needs: deploy-lorawan-server
    uses: ./.github/workflows/deploy_component.yml
    with:
      component-path: 'mqtt-client'
    secrets: inherit

  deploy-api-emasa:
    needs: deploy-lorawan-server
    uses: ./.github/workflows/deploy_component.yml
    with:
      component-path: 'api-rest-emasa'
    secrets: inherit

  cleanup-volumes:
    name: Cleanup Unused Docker Volumes
    needs: [deploy-mqtt-client, deploy-api-emasa]
    runs-on: ubuntu-22.04
    steps:
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          
      - name: Prune unused Docker volumes
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            docker volume prune -f
          EOF
